### ISSUE TITLE
Slowness or user error?

### ISSUE THREAD

**Issue by RyanTheAllmighty** [mini2Dx/gettext#1]
Hi there,

I'm using this library to localise and generate pot files from my source code.

Here's a quick summary as to my project:

Number of Java files: Around 230
Lines of Java code: Around 35,000

Currently the JVM exits with out of memory and gc overhead errors (wven when running with JVM args to bump up to 2GB memory) when running `.\gradlew generatePots` with the following in my `build.gradle`:

```
gettext {
    template {
        srcDir = 'src'
        include = 'main/java/com/atlauncher/**/*.java'
        outputFilename = 'template.pot'
    }
}
```

One stacktrace I've seen:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.resize(HashMap.java:704)
        at java.util.HashMap.putVal(HashMap.java:663)
        at java.util.HashMap.put(HashMap.java:612)
        at org.antlr.v4.runtime.misc.DoubleKeyMap.put(DoubleKeyMap.java:26)
        at org.antlr.v4.runtime.atn.PredictionContext.mergeArrays(PredictionContext.java:461)
        at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:174)
        at org.antlr.v4.runtime.atn.PredictionContext.mergeArrays(PredictionContext.java:395)
        at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:174)
        at org.antlr.v4.runtime.atn.PredictionContext.mergeSingletons(PredictionContext.java:225)
        at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:155)
        at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:154)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1529)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
```

Since it scans source files to extract the template, I'm guessing it's just too much source code to go through?

Even when I limit the `include` to scan just one directory with around 40 files and a few thousand lines, it takes about 2 minutes.

Is there something I'm possibly doing wrong, or just the way that the plugin works because it has to scan everything?

Any advice/help would be great. or if it's just a limitation of parsing so many files/lines of code, then I guess I might just be out of luck?

Thanks

**Comment by tomcashman** [comment]
We currently use ANTLR to parse the Java files so perhaps there is some optimisations needed for how it's used. Currently it creates a new parser per file but maybe there's a better way to reuse the parser.

**Comment by tomcashman** [comment]
Would you be able to test the latest repo version on your set up to see if it resolves your issue? On my local test I found a 50% reduction in memory usage but I think your project is much larger than mine.

To test it, clone the repo and run ```./gradlew clean install``` and then set the version to 1.1.0-SNAPSHOT in your project. If your project uses Gradle, make sure ```mavenLocal()``` in your repositories section.

**Comment by RyanTheAllmighty** [comment]
Thanks for the quick response :)

It looks much much faster now, scanning and generating for my entire project in 59 seconds now instead of throwing out of memory at 10 minutes.

**Comment by RyanTheAllmighty** [comment]
If I remove my custom JVM args for gradle, it also builds just as fast with the defaults, so looks to have completely resolved the issue :)

**Comment by tomcashman** [comment]
Awesome :)
